// @ts-nocheck
(function (api) {
    var MAP_BEGIN = "// --- string map (edit labels below) ---";
    var MAP_END = "// --- end string map ---";

    function quote(value) {
        value = String(value || "");
        value = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
        value = value.replace(/\r/g, "\\r").replace(/\n/g, "\\n");
        return '"' + value + '"';
    }

    function joinLines(lines) {
        return lines.join("\n");
    }

    function defaultMapLabel(pitch, labelMode) {
        if (labelMode === "drums" && api.GM_DRUM_NAMES && api.GM_DRUM_NAMES[pitch]) {
            return api.GM_DRUM_NAMES[pitch];
        }
        if (typeof api.noteNameForPitch === "function") {
            return api.noteNameForPitch(pitch);
        }
        return String(pitch);
    }

    api.buildMidiMapDefaultLabels = function (pitches, labelMode) {
        var labels = [];
        var i;
        for (i = 0; i < pitches.length; i += 1) {
            labels.push([pitches[i], defaultMapLabel(pitches[i], labelMode || "notes")]);
        }
        return labels;
    };

    function formatNoteLabelsBlock(noteLabels) {
        var lines = [MAP_BEGIN, "var noteLabels = ["];
        var i;
        for (i = 0; i < noteLabels.length; i += 1) {
            lines.push(
                "    [" +
                    Math.round(noteLabels[i][0]) +
                    ", " +
                    quote(noteLabels[i][1]) +
                    "]" +
                    (i < noteLabels.length - 1 ? "," : "")
            );
        }
        lines.push("];");
        lines.push(MAP_END);
        return lines;
    }

    api.formatMidiMapNoteLabelsBlock = formatNoteLabelsBlock;

    api.buildMidiMapExpression = function (options) {
        var sourceLayer = options.sourceLayerName || "MIDI";
        var pitchSlider = options.pitchSliderName || "T01 Ch01 pitch";
        var defaultLabel = quote(options.defaultLabel || "");
        var mapBlock = formatNoteLabelsBlock(options.noteLabels || []);

        return joinLines(
            [
                "// Generated by ReOm MIDI Map",
                "var midiLayer = thisComp.layer(" + quote(sourceLayer) + ");",
                "var pitchSliderName = " + quote(pitchSlider) + ";",
                "var defaultLabel = " + defaultLabel + ";",
                ""
            ]
                .concat(mapBlock)
                .concat([
                    "function sliderByName(effectName) {",
                    '    try { return midiLayer.effect(effectName)("Slider"); } catch (e) { return null; }',
                    "}",
                    "function lastKeyAtOrBefore(prop, t) {",
                    "    if (!prop || prop.numKeys < 1) { return 0; }",
                    "    var n = prop.nearestKey(t).index;",
                    "    if (prop.key(n).time > t) { n--; }",
                    "    return n;",
                    "}",
                    "function labelForPitch(pitch) {",
                    "    var i;",
                    "    for (i = 0; i < noteLabels.length; i++) {",
                    "        if (noteLabels[i][0] === pitch) { return noteLabels[i][1]; }",
                    "    }",
                    "    return String(pitch);",
                    "}",
                    "try {",
                    "    (function () {",
                    "        var s = sliderByName(pitchSliderName);",
                    "        var n = lastKeyAtOrBefore(s, time);",
                    "        if (n < 1) { return defaultLabel; }",
                    "        var pitch = Math.round(s.key(n).value);",
                    "        if (pitch <= 0) { return defaultLabel; }",
                    "        return labelForPitch(pitch);",
                    "    })();",
                    "} catch (e) {",
                    "    defaultLabel;",
                    "}"
                ])
        );
    };

    api.parseMidiMapNoteLabelsFromExpression = function (expression) {
        var text = String(expression || "");
        var begin = text.indexOf(MAP_BEGIN);
        var end = text.indexOf(MAP_END);
        var block;
        var labels = [];
        var re = /\[\s*(\d+)\s*,\s*"((?:\\.|[^"\\])*)"\s*\]/g;
        var match;

        if (begin < 0 || end < 0 || end <= begin) {
            return null;
        }
        block = text.substring(begin, end);
        while ((match = re.exec(block))) {
            labels.push([
                parseInt(match[1], 10),
                match[2].replace(/\\n/g, "\n").replace(/\\r/g, "\r").replace(/\\"/g, '"').replace(/\\\\/g, "\\")
            ]);
        }
        return labels.length ? labels : null;
    };

    api.prepareMidiMapExpression = function (comp, sourceLayer, options) {
        var range;
        var noteLabels;
        var labelMode;
        var expression;
        var state;

        options = options || {};
        if (!sourceLayer) {
            throw new Error("Select an imported MIDI layer before generating a MIDI Map expression.");
        }
        range = api.collectPitchValuesFromLayer(sourceLayer, options);
        if (!range.pitches.length) {
            throw new Error(
                'No pitch values were found on layer "' +
                    sourceLayer.name +
                    '".' +
                    (range.pitchSliderName ? ' Pitch slider: "' + range.pitchSliderName + '".' : "")
            );
        }
        labelMode = options.labelMode || "notes";
        noteLabels = api.buildMidiMapDefaultLabels(range.pitches, labelMode);
        expression = api.buildMidiMapExpression({
            sourceLayerName: sourceLayer.name,
            pitchSliderName: range.pitchSliderName || api.resolvePitchSliderName(sourceLayer, options),
            noteLabels: noteLabels,
            defaultLabel: options.defaultLabel || ""
        });
        state = {
            pitches: range.pitches,
            pitchSliderName: range.pitchSliderName || api.resolvePitchSliderName(sourceLayer, options),
            sourceLayerName: sourceLayer.name,
            labelMode: labelMode
        };
        return {
            expression: expression,
            noteLabels: noteLabels,
            range: range,
            state: state,
            summary:
                range.pitches.length +
                " pitch" +
                (range.pitches.length === 1 ? "" : "es") +
                " (" +
                range.min +
                "\u2013" +
                range.max +
                ") from " +
                sourceLayer.name +
                "."
        };
    };

    api.regenerateMidiMapExpression = function (state, labelMode) {
        var noteLabels;
        if (!state || !state.pitches || !state.pitches.length) {
            throw new Error("Generate a MIDI Map from the selected layer first.");
        }
        noteLabels = api.buildMidiMapDefaultLabels(state.pitches, labelMode || "notes");
        return api.buildMidiMapExpression({
            sourceLayerName: state.sourceLayerName,
            pitchSliderName: state.pitchSliderName,
            noteLabels: noteLabels,
            defaultLabel: ""
        });
    };

    function setPropExpression(prop, expression) {
        if (!prop) {
            return false;
        }
        try {
            if (prop.canSetExpression === false) {
                return false;
            }
            prop.expression = expression;
            if (typeof prop.expressionEnabled !== "undefined") {
                prop.expressionEnabled = true;
            }
            return true;
        } catch (e) {}
        return false;
    }

    api.createMidiMapTextLayer = function (comp, sourceLayer, expression) {
        var layer;
        var textProp;
        if (!comp || !comp.layers || !comp.layers.addText) {
            throw new Error("Could not create a text layer in the active composition.");
        }
        if (!expression) {
            throw new Error("The MIDI Map expression is empty.");
        }
        layer = comp.layers.addText(" ");
        layer.name = api.limitEffectName("MIDI Map " + (sourceLayer && sourceLayer.name ? sourceLayer.name : "MIDI"));
        layer.comment =
            "Generated by ReOm MIDI Map\nSource: " + (sourceLayer && sourceLayer.name ? sourceLayer.name : "MIDI");
        textProp = layer.property("Source Text");
        if (!textProp || textProp.canSetExpression === false) {
            throw new Error("The text layer Source Text property cannot receive expressions.");
        }
        if (!setPropExpression(textProp, expression)) {
            throw new Error("Could not apply the MIDI Map expression to Source Text.");
        }
        return {
            layerName: layer.name,
            expression: expression
        };
    };
})(ReOmMIDI);
