const fs = require("fs");
const path = require("path");
const { root, VERSION, readSource } = require("./source-loader");

const output = path.join(root, "re_om_midi.jsx");
const sourceFiles = [
  "src/core/namespace.jsx",
  "src/core/midi-file.jsx",
  "src/ae/layer-utils.jsx",
  "src/ae/keyframes.jsx",
  "src/ae/timing-layers.jsx",
  "src/ae/expressions.jsx",
  "src/ae/midi-map.jsx",
  "src/ae/tone-layer.jsx",
  "src/ae/screen-flip.jsx",
  "src/ae/drum-machine.jsx",
  "src/ae/drum-sequencer.jsx",
  "src/ae/ui.jsx",
  "src/main.jsx"
];

const banner = `/*
 ReOm MIDI v${VERSION}
 Modernized After Effects MIDI import script.

 Copyright (c) 2026 Fuou Marinas
 Licensed under the GNU General Public License v3 (GPLv3).
 See LICENSE file for full license terms.

 Obfuscation notice:
 In keeping with GPLv3, this code must remain readable. Obfuscated or
 binarized versions (.jsxbin) are not permitted without also providing
 the corresponding readable source files (.jsx).

 Generated by scripts/build.js. Edit files in src/ instead of this bundle.
 Original script lineage: Omino MIDI File Reader / om_midi.jsx by David Van Brink.
*/

`;

const body = sourceFiles
  .map((relativePath) => {
    return `// ---- ${relativePath.replace(/\\/g, "/")} ----\n${readSource(relativePath)}\n`;
  })
  .join("\n");

fs.writeFileSync(output, banner + body, "utf8");
console.log(`Built ${path.relative(root, output)} v${VERSION} from ${sourceFiles.length} source files.`);
