const fs = require("fs");
const path = require("path");
const { root, VERSION, readSource } = require("./source-loader");

const output = path.join(root, "re_om_midi.jsx");
const sourceFiles = [
  "dist/compiled/core/namespace.jsx",
  "dist/compiled/core/property-utils.jsx",
  "dist/compiled/core/midi-file.jsx",
  "dist/compiled/ae/layer-utils.jsx",
  "dist/compiled/ae/keyframes.jsx",
  "dist/compiled/ae/timing-layers.jsx",
  "dist/compiled/ae/expressions.jsx",
  "dist/compiled/ae/midi-map.jsx",
  "dist/compiled/ae/tone-layer.jsx",
  "dist/compiled/ae/screen-flip.jsx",
  "dist/compiled/ae/drum-machine.jsx",
  "dist/compiled/ae/drum-sequencer.jsx",
  "dist/compiled/ae/ui.jsx",
  "dist/compiled/main.jsx"
];

const banner = `#targetengine "reom_midi"
/*
 ReOm MIDI v${VERSION}
 Modernized After Effects MIDI import script.

 Copyright (c) 2026 Fuou Marinas
 Licensed under the GNU General Public License v3 (GPLv3).
 See LICENSE file for full license terms.

 Obfuscation notice:
 In keeping with GPLv3, this code must remain readable. Obfuscated or
 binarized versions (.jsxbin) are not permitted without also providing
 the corresponding readable source files (.jsx).

 Generated by scripts/build.js from TypeScript sources in src/. Edit src/*.ts, not this bundle.
 Original script lineage: Omino MIDI File Reader / om_midi.jsx by David Van Brink.
*/

`;

function buildBundle() {
  const body = sourceFiles
    .map((relativePath) => {
      return `// ---- ${relativePath.replace(/\\/g, "/")} ----\n${readSource(relativePath)}\n`;
    })
    .join("\n");

  fs.writeFileSync(output, banner + body, "utf8");
  console.log(`Built ${path.relative(root, output)} v${VERSION} from ${sourceFiles.length} source files.`);
}

if (require.main === module) {
  buildBundle();
}

module.exports = {
  sourceFiles,
  buildBundle
};
